### PR TITLE
Symbols documentation

### PR DESCRIPTION
**Pull request by aminnairi**
Hi there!

I wanted to make a documentation page for Symbols. I am no expert and really new to this don't get me wrong It is still wip and there is a lot more we can do with symbols but I had to do this one with those cool examples. Will certainly add new ones soon as I get more confidence and experience with these new bad boys.

### CODE REVIEW

**Comment by shardy613** [comment]
Hey there @aminnairi! 👋 

Thanks for taking time to make a PR! I will take a look at this very soon, I have worked with Symbols before and they are an interesting aspect to the `ecmascript 6` spec.

**Comment by aminnairi** [comment]
Got it, I'll get into the generators then!

**Comment by shardy613** [comment]
Awesome! Really looking forward to your contributions.

**Comment by shardy613** [comment]
Sounds good, thanks for the update and good luck on your project!

**Pull request closed without merging**
