### PR TITLE
Remove all inconsistent usage of let instead const

### LINKED ISSUE #7: Inconsistent usage of "let" and "const" in code examples
In the code examples `let` is often used for variables that are not mutated. `const` is better suited for these variables. Please use `const` when the value is not mutated.

### PR DESCRIPTION
**Pull request by fernandoguedes**
Close #7

### CODE REVIEW

**Comment by fernandoguedes** [comment]
I will fix, thanks for the review.

**Comment by shardy613** [comment]
༼ つ ◕_ ◕ ༽つ ?

**Comment by shardy613** [comment]
༼ つ ◕_ ◕ ༽つ ?

**Comment by shardy613** [comment]
༼ つ ◕_ ◕ ༽つ ?

**Comment by fernandoguedes** [comment]
Done.

**Comment by shardy613** [comment]
Thank you so much for your work, I'll review this shortly!

**Comment by shardy613** [comment]
https://github.com/shardy613/es6-notes/blob/master/CONTRIBUTORS.md :))

**Pull request merged**
